# -*- coding: utf-8 -*-
"""ReefDatasetGen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0HL0jcRhdXSUHSY3rw-Ng6_U8Vg-_n5
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
import numpy as np

ranges = [
    (380,450),   # Calcium ppm
    (8,12),    # Alkalinity dKH
    (1200,1400),  # Magnesium ppm
    (0.01,0.05),    # Phosphate ppm
    (0,15),     # Nitrate ppm
    (0,5),    #Nitrite ppm
    (0,5),    #Ammonia ppm
    (32, 35),    # Salinity  ppt
    (76,80),    # Temperature degrees F
    (8.0, 8.3),     # pH
    (250, 400)    # ORP mV
]

measures = ["Calcium", "Alkalinity", "Magnesium", "Phosphate", "Nitrate", "Nitrite", "Ammonia", "Salinity", "Temperature", "pH", "ORP"]

# VAE Architecture
class VAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        # Decoder
        self.fc2 = nn.Linear(latent_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, input_dim)

    def encode(self, x):
        h1 = torch.relu(self.fc1(x))
        return self.fc_mu(h1), self.fc_logvar(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h2 = torch.relu(self.fc2(z))
        return torch.sigmoid(self.fc3(h2))

    def forward(self, x):
        mu, logvar = self.encode(x.view(x.size(0), -1))
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

# Loss function
def loss_function(recon_x, x, mu, logvar, beta):
  MSE = nn.functional.mse_loss(recon_x, x.view(x.size(0), -1), reduction='sum')
  KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
  return MSE + beta * KLD

# Training the VAE
def train(model, train_loader, optimizer, epoch, device, beta):
    model.train()
    train_loss = 0
    for _ , (data,) in enumerate(train_loader):
        optimizer.zero_grad()
        data = data.to(device)
        recon_batch, mu, logvar = model(data)
        loss = loss_function(recon_batch, data, mu, logvar, beta)
        loss.backward()
        train_loss += loss.item()
        optimizer.step()
    print(f'Epoch {epoch}, Loss: {train_loss / len(train_loader.dataset)}')
    return train_loss / len(train_loader.dataset)

def generate_random_walk(model, T, latent_dim, step_size, device="cpu"):
    model.eval()
    z = torch.zeros(T, latent_dim, device=device)

    z[0] = torch.randn(latent_dim, device=device)

    for t in range(1, T):
        z[t] = z[t - 1] + step_size * torch.randn(latent_dim, device=device)

    x = model.decode(z)
    x_gen = torch.zeros_like(x)
    for i, (low, high) in enumerate(ranges):
        x_gen[:, i] = x[:, i] * (high - low) + low
    return x_gen

def main():
    n_samples = 50
    n_col = len(ranges)
    x_train = np.zeros((n_samples, n_col))
    for i, (low, high) in enumerate(ranges):
      x_train[:,i] = (np.random.uniform(low,high,n_samples) - low) / (high-low)
    x_train = torch.tensor(x_train, dtype=torch.float32)
    train_dataset = TensorDataset(x_train)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    vae = VAE(input_dim=n_col, hidden_dim=16, latent_dim=32)
    vae.to(device)
    optimizer = optim.Adam(vae.parameters(), lr=1e-3)

    loss_plot = []
    for epoch in range(1, 500):
        loss_plot.append(train(vae, train_loader, optimizer, epoch, device, 0.25))
    print("Training Complete")

    plt.figure(figsize=(10,5))
    plt.plot(loss_plot, label = 'Training Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.show()

    with torch.no_grad():
        x = generate_random_walk(vae, 100, 32, 0.1)


    fig, axes = plt.subplots(1, n_col, figsize=(120, 10))
    for i in range(n_col):
        axes[i].plot(x[:, i])
        axes[i].set_title(measures[i])
    plt.show()
    print(x.shape)

    torch.save(vae.state_dict(),'reef_vae.pth')

if __name__ == "__main__":
    main()